services:
  - type: web
    name: dtabdullahcirit-site
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python backend/server.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.4
      - key: COOKIE_SECURE
        value: true
      - key: APPOINTMENT_EMAIL_USER
        value: dtabdullahcirit@gmail.com
      - key: APPOINTMENT_EMAIL_TO
        value: dtabdullahcirit@gmail.com
      - key: APPOINTMENT_EMAIL_PASS
        sync: false
      - key: ADMIN_PASSWORD_HASH
        sync: false
